# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vector_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import vector_models_pb2 as vector__models__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14vector_service.proto\x12\x06vector\x1a\x13vector_models.proto\")\n\x13GetEmbeddingRequest\x12\x12\n\ninput_text\x18\x01 \x01(\t\"F\n\x14GetEmbeddingResponse\x12.\n\x13resulting_embedding\x18\x01 \x01(\x0b\x32\x11.vector.Embedding\"B\n\x14GetSimilarityRequest\x12*\n\x0finput_embedding\x18\x01 \x01(\x0b\x32\x11.vector.Embedding\"8\n\x15GetSimilarityResponse\x12\x0f\n\x07matches\x18\x01 \x03(\t\x12\x0e\n\x06scores\x18\x02 \x03(\x02\"7\n\x10LoadQueryRequest\x12\x0f\n\x07queries\x18\x01 \x03(\t\x12\x12\n\nthresholds\x18\x02 \x03(\x02\"\x13\n\x11LoadQueryResponse2\xec\x01\n\rVectorService\x12I\n\x0cGetEmbedding\x12\x1b.vector.GetEmbeddingRequest\x1a\x1c.vector.GetEmbeddingResponse\x12L\n\rGetSimilarity\x12\x1c.vector.GetSimilarityRequest\x1a\x1d.vector.GetSimilarityResponse\x12\x42\n\x0bLoadQueries\x12\x18.vector.LoadQueryRequest\x1a\x19.vector.LoadQueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETEMBEDDINGREQUEST']._serialized_start=53
  _globals['_GETEMBEDDINGREQUEST']._serialized_end=94
  _globals['_GETEMBEDDINGRESPONSE']._serialized_start=96
  _globals['_GETEMBEDDINGRESPONSE']._serialized_end=166
  _globals['_GETSIMILARITYREQUEST']._serialized_start=168
  _globals['_GETSIMILARITYREQUEST']._serialized_end=234
  _globals['_GETSIMILARITYRESPONSE']._serialized_start=236
  _globals['_GETSIMILARITYRESPONSE']._serialized_end=292
  _globals['_LOADQUERYREQUEST']._serialized_start=294
  _globals['_LOADQUERYREQUEST']._serialized_end=349
  _globals['_LOADQUERYRESPONSE']._serialized_start=351
  _globals['_LOADQUERYRESPONSE']._serialized_end=370
  _globals['_VECTORSERVICE']._serialized_start=373
  _globals['_VECTORSERVICE']._serialized_end=609
# @@protoc_insertion_point(module_scope)
